version: '3.7'

services:
  makepdfs:
    container_name: markdown-to-pdf
    build:
      context: .
      dockerfile: Dockerfile
    image: "docker.pkg.github.com/baileyjm02/markdown-to-pdf/convert:${TAG:-latest}"
